
# Singleton service factory configuration/IoC injection
service.singletons:
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          parameters:
            registryRetryPeriod: '30000'
  - com.networknt.consul.client.ConsulClient:
      - com.networknt.consul.client.ConsulClientImpl
  - com.networknt.registry.Registry:
      - com.networknt.consul.ConsulRegistry
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster
  - com.networknt.market.service.MarketService:
      - com.networknt.market.service.MarketServiceImpl

#--------------------------------------------------------------------------------
# service-define.yml
#--------------------------------------------------------------------------------
service-define.serviceMap:
  petstore:
    {  serviceId: "com.networknt.petstore-service-api-3.0.1", protocol: "https",   environment: null , requestKey: null}
  bookstore:
    {  serviceId: "com.networknt.bookstore-service-api-3.0.1", protocol: "https",   environment: null , requestKey: null}
  foodstore:
    {  serviceId: "com.networknt.foodstore-service-api-3.0.1", protocol: "https",   environment: null , requestKey: null}
  computerstore:
    {  serviceId: "com.networknt.computerstore-service-api-3.0.1", protocol: "https",   environment: null , requestKey: null}


#--------------------------------------------------------------------------------
# server.yml
#--------------------------------------------------------------------------------

server.enableRegistry: true
server.httpsPort: 8991
server.environment: sit

#--------------------------------------------------------------------------------
# consul.yml
#--------------------------------------------------------------------------------
consul.consulUrl: http://consul:8500
consul.ttlCheck: true
